name: Schedule Test

on:
  schedule:
    - cron: "37 6 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Scheduled workflow works"
